### PR TITLE
Merge template refresh

### LINKED ISSUE #117: "Release" the updated template
Work for https://github.com/AlexsLemonade/training-admin/issues/1017 is going to take place in with a "base branch" called `template-refresh`, so the final step is to merge into `main`. This issue tracks the final merge, which is not _quite_ a release but sort of!

That said, I suppose it can't entirely hurt to, before this gets merged, tag/release the current `main` branch and then tag as new release after merging. That can be decided later.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #117 

Homestretch! This PR merges `template-refresh` into `main`. I am filing this on a Friday, so I certainly do not expect it to be reviewed or merged today, but this does feel good to file! 

For review, you'll want to explore the site serving under both `"remote"` and `"in-person"` configurations. 

Noting this bit from #117 - 
> That said, I suppose it can't entirely hurt to, before this gets merged, tag/release the current main branch and then tag as new release after merging. That can be decided later.

It is now later 🎉 ! I still think versioning is not a terrible idea, since this is a public template. Any thoughts on this from reviewers? We'd want to reflect a major bump, so we _could_ do - 
- pre refresh, `v0.1` (at least `0.<something>`)
- post refresh merge, `v1.0` (that said, we might want to wait on this one until we can finalize #147)

### CODE REVIEW

**Comment by jashapiro** [comment]
> It is now later 🎉 ! I still think versioning is not a terrible idea, since this is a public template. Any thoughts on this from reviewers? We'd want to reflect a major bump, so we _could_ do -
> 
> * pre refresh, `v0.1` (at least `0.<something>`)
> * post refresh merge, `v1.0` (that said, we might want to wait on this one until we can finalize [Add additional instructions for external workshops #147](https://github.com/AlexsLemonade/training-specific-template/issues/147))

I think tagging by year probably makes the most sense here, rather real version numbers.

**Review by jashapiro — APPROVED** [review]
I loaded and tested both versions of the website, clicking around at many but not all links, and things seemed to be fine. 

Before merging this, it probably makes sense to tag the previous version: I'll leave it to you exactly how to do the tags, but as I said, I would probably favor dates over semantic versions.

**Comment by sjspielman** [comment]
> Before merging this, it probably makes sense to tag the previous version: I'll leave it to you exactly how to do the tags, but as I said, I would probably favor dates over semantic versions.

I do like the idea of dates, but I'm not sure about using just a year. What do you think about `2023-09` (current) and `2023-10` (after merge)?

**Comment by sjspielman** [comment]
probably should have tagged you @jashapiro ☝️

**Comment by jashapiro** [comment]
> > Before merging this, it probably makes sense to tag the previous version: I'll leave it to you exactly how to do the tags, but as I said, I would probably favor dates over semantic versions.
> 
> I do like the idea of dates, but I'm not sure about using just a year. What do you think about `2023-09` (current; or really any other previous year/month combo since `2020-03`!) and `2023-10` (after merge)?

That is fine. Maybe `2020.03` for no accidental subtraction reasons?

**Pull request merged**
