### PR TITLE
Populate additional resources

### LINKED ISSUE #120: Populate `additional-resources` directory
_Broken out of #109_

After the `additional-resources` directory has been established, let's get some contents into it:

- Create new file `single-cell-resources.md` with contents:
  - Contents from [resources for continued single-cell learning](https://github.com/AlexsLemonade/2023-june-training/blob/4ccd2df912fa636db1e7c2156df650132be8d900/workshop/single-cell-resources.md) 
  - Finding practice single-cell datasets, broken out of `resources-for-consultation-sessions.md`
- Create new file `bulk-resources.md` with contents:
    - Finding practice bulk/microarray datasets content, broken out of `resources-for-consultation-sessions.md`
   - Transcriptome indices content, broken out of `resources-for-consultation-sessions.md`
- Move in `R-prep.md` rename to `R-resources.md` 
  - At this point we can delete the directory `optional-workshop-prep`
  - Also, ensure that relative links to this still work!
- Move in `template-scripts/wget_TEMPLATE.sh`, which we still want to link from `working-with-your-own-data.md`, so also a good time to ensure the relative link will still works
- A `screenshots` directory with relevant content to these markdown files
- ⚠️ change from original plan: Let's also move `software-setup.md` into this directory, from `workshop/`, since it is not a navbar page!

### PR DESCRIPTION
**Pull request by sjspielman**
**⚠️ Stacked on #126**
Closes #120 

#126 established the `additional-resources` directory, so this PR takes next steps to actually populate this directory with some files.
This includes R, single-cell, and bulk resources files, which will end up being linked from `workshop/workshop-resources` (in PR #129). There were no screenshots to move here, so that is a nice treat.

Other changes here include..
- moving `software-setup.md` into `additional-resources` (as this page is not in `header_pages` it does not belong in `workshop`)
- moving in `template-scripts/wget_TEMPLATE.sh` 

I updated relative links throughout to accommodate these specific file path changes as well.

### CODE REVIEW

**Comment by sjspielman** [comment]
note to reviewers - there may be some typos, but those are fixed in a stacked PR #131 so it's ok for this PR to leave them!

**Comment by Jen-OMalley** [comment]
> This all look goods, except the `template-scripts/wget_TEMPLATE.sh` link isn't working for me. But maybe that's because of other PRs that haven't been merged yet?

Meant to tag you @sjspielman!

**Comment by sjspielman** [comment]
> This all look goods, except the `template-scripts/wget_TEMPLATE.sh` link isn't working for me. But maybe that's because of other PRs that haven't been merged yet?

Ahhhh yes, I assume you mean this updated link, copied here from this branch:
https://github.com/AlexsLemonade/training-specific-template/blob/0327a93c480b94de141bd61d21cedeeb3f8c82a9/workshop/working-with-your-own-data.md?plain=1#L56

This one is not expected to work since the `{{site.repository_url}}` aspect of the URL only gets automatically filled in when the website is formally created. The thing to check here is that indeed `wget-TEMPLATE.sh` lives in the folder that link specifies: `additional-resources/template-scripts/wget-TEMPLATE.sh`. By my eye it does and all is spelled correctly (so, this is where you can focus a review for that link!) so this is expected to work at the end of the day! 

Is this what you are referring to or is there another spot?

**Comment by Jen-OMalley** [comment]
> > This all look goods, except the `template-scripts/wget_TEMPLATE.sh` link isn't working for me. But maybe that's because of other PRs that haven't been merged yet?
> 
> Ahhhh yes, I assume you mean this updated link, copied here from this branch:
> 
> https://github.com/AlexsLemonade/training-specific-template/blob/0327a93c480b94de141bd61d21cedeeb3f8c82a9/workshop/working-with-your-own-data.md?plain=1#L56
> 
> This one is not expected to work since the `{{site.repository_url}}` aspect of the URL only gets automatically filled in when the website is formally created. The thing to check here is that indeed `wget-TEMPLATE.sh` lives in the folder that link specifies: `additional-resources/template-scripts/wget-TEMPLATE.sh`. By my eye it does and all is spelled correctly (so, this is where you can focus a review for that link!) so this is expected to work at the end of the day!
> 
> Is this what you are referring to or is there another spot?

Gotcha! Figured there was a reason! Then everything looks correct to me, as well.

**Review by Jen-OMalley — APPROVED** [review]
👍🏻

**Pull request merged**
